"""Close the loop: turn a detected incident into the SigNoz alert that would have
caught it, created through the same MCP server Cerberus reads from.

`build_alert` is pure (offline-testable). `arm` performs the two live MCP writes —
ensure a notification channel exists, then create the rule — and is idempotent so
re-running a demo doesn't pile up duplicate rules.
"""

import json

from cerberus.signoz_client import call_tool

CHANNEL = "cerberus-webhook"


CHANNEL_URL = "http://localhost:9999/cerberus-alerts"


def build_alert(service: str, token_baseline: int = 1000) -> dict:
    """The SigNoz alert rule that catches a prompt-token spike — the runaway prompt
    that is the root cause behind the cost spikes Cerberus flags. A TRACES_BASED
    threshold rule over max(gen_ai.usage.input_tokens) per service."""
    return {
        "alert": f"Cerberus — prompt token spike ({service})",
        "alertType": "TRACES_BASED_ALERT",
        "description": (
            "An agent LLM step used far more input tokens than baseline — the runaway "
            "prompt behind cost spikes. Generated by Cerberus from a detected incident."
        ),
        "ruleType": "threshold_rule",
        "version": "v5",
        "schemaVersion": "v2alpha1",
        "condition": {
            "compositeQuery": {
                "queryType": "builder",
                "panelType": "graph",
                "unit": "",
                "queries": [
                    {
                        "type": "builder_query",
                        "spec": {
                            "name": "A",
                            "signal": "traces",
                            "stepInterval": 60,
                            "aggregations": [{"expression": "max(gen_ai.usage.input_tokens)"}],
                            "limit": 100,
                            "order": [
                                {
                                    "key": {"name": "max(gen_ai.usage.input_tokens)"},
                                    "direction": "desc",
                                }
                            ],
                            "filter": {"expression": f"service.name = '{service}'"},
                            "groupBy": [
                                {
                                    "name": "service.name",
                                    "fieldContext": "resource",
                                    "fieldDataType": "string",
                                }
                            ],
                            "legend": "{{service.name}}",
                        },
                    }
                ],
            },
            "selectedQueryName": "A",
            "thresholds": {
                "kind": "basic",
                "spec": [
                    {
                        "name": "warning",
                        "op": "above",
                        "matchType": "at_least_once",
                        "target": token_baseline,
                        "channels": [CHANNEL],
                    }
                ],
            },
        },
        "evaluation": {"kind": "rolling", "spec": {"evalWindow": "5m", "frequency": "1m"}},
        "labels": {"severity": "warning", "generated_by": "cerberus"},
        "annotations": {
            "summary": "Agent prompt token spike on {{$labels.service.name}}",
            "description": (
                "max input tokens crossed {{$threshold}} — inspect the failing judge step."
            ),
        },
    }


def _names(payload: str, key: str) -> set[str]:
    try:
        data = json.JSONDecoder().raw_decode(payload.lstrip())[0]
    except (json.JSONDecodeError, AttributeError):
        return set()
    return {row.get(key) for row in (data.get("data") or []) if isinstance(row, dict)}


def arm(service: str, token_baseline: int = 1000, caller=call_tool) -> dict:
    """Ensure the notification channel and the alert rule both exist. Idempotent:
    skips whichever already exists so a repeated demo run is a no-op. Returns what
    was created or found. `caller` is injectable for offline tests."""
    if CHANNEL not in _names(caller("signoz_list_notification_channels", {}), "name"):
        caller(
            "signoz_create_notification_channel",
            {"name": CHANNEL, "type": "webhook", "webhook_url": CHANNEL_URL},
        )

    alert = build_alert(service, token_baseline)
    if alert["alert"] in _names(caller("signoz_list_alert_rules", {}), "alert"):
        return {"alert": alert["alert"], "created": False, "channel": CHANNEL}

    caller("signoz_create_alert", {"alert": alert["alert"], **alert})
    return {"alert": alert["alert"], "created": True, "channel": CHANNEL}
